#!/bin/bash

if [ "$1" == "cliente" ]; then
    echo "Cliente: gradlew run -Papp=cliente.App ${@:2}"
    ./gradlew run --console rich -q -Papp=cliente.App "${@:2}"
elif [ "$1" == "clienteweb" ]; then
    echo "Cliente: gradlew bootRun -Papp=cliente.App web ${@:2}"
    ./gradlew bootRun -Papp=cliente.App "${@:2}"
elif [ "$1" == "servidor" ]; then
    echo "Servidor: gradlew run -Papp=servidor.App ${@:2}"
    ./gradlew --console rich -q run -Papp=servidor.App "${@:2}"
else
    echo "Usage: $0 cliente|servidor [other args]"
    exit 1
fi
