#!/bin/bash

OPTS="--console plain -I logger.init.gradle.kts"

if [ "$1" == "cliente" ]; then
    APP="-Papp=cliente.App"
elif [ "$1" == "servidor" ]; then
    APP="-Papp=servidor.App"
else
    echo "Usage: $0 cliente|servidor [other args]"
    exit 1
fi

if [ "$#" -gt 1 ]; then
    if [[ "$2" == *"-w"* ]]; then
        ./gradlew $OPTS $APP bootRun --args="$2"
    else
        ./gradlew $OPTS $APP run --args="$2"
    fi
else
    ./gradlew $OPTS $APP run
fi
