#!/bin/bash

OPTS="--console plain -I logger.init.gradle.kts"

if [ "$1" == "cliente" ]; then
    APP="-Papp=cliente.App"
elif [ "$1" == "servidor" ]; then
    APP="-Papp=servidor.App"
else
    echo "Usage: $0 cliente|servidor [\"args\"] [http port]"
    exit 1
fi

if [ "$#" -gt 2 ]; then
    PORT="env SERVER_PORT=$3"
fi

CMD="$PORT ./gradlew $OPTS $APP"

if [ "$#" -gt 1 ]; then
    if [[ "$2" == *"-w"* ]]; then
        $CMD bootRun --args="$2"
    else
        $CMD run --args="$2"
    fi
else
    $CMD run
fi
